### ISSUE TITLE
Projections for the example data?

### ISSUE THREAD

**Issue by NateMietk** [bhaskarvk/tilegramsR#7]
It does not seem as if any of the example data have projections.  Can you provide the appropriate CRSs for the sf objects and general size of each voxel given the projection?  For example, the sf_Pitch_US_Population_2016_v1 data may be in albers equal area at 25km per voxel.  Thanks!

**Comment by bhaskarvk** [comment]
@NateMietk 
 While it may be the case that various tilegrams from different providers are using some well known CRS for encoding, it really should be treated as unreferenced.The polygon data is not really geographical in nature and as such is not georeferenced, therefore I haven't put any CRSs to any of the SF objects. For any joining with other data you should use the "state" attribute rather than attempt any sort of geographical join. If having a CRS is important, you can always set the CRS of the sf object in your code. 
Btw the Pitch Interactive tilegram is defi. not albers eq.

**Comment by NateMietk** [comment]
Thanks for the response.  It is very helpful to understand why there is no reference system.  Much appreciated.
